# Generated by Django 3.0.6 on 2020-05-29 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugMusicApp', '0002_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='Profile',
            new_name='profile',
        ),
    ]
